### PR TITLE
#380 - Add option for escape key to close popup

### PR DESCRIPTION
**Pull request by scotthovestadt**
Option added: ````filterClosedOnEscPressed````

Off by default to preserve existing behavior.

### CODE REVIEW

**Comment by scotthovestadt** [comment]
Resolves issue #380

Please let me know if you're willing to merge it in.

**Comment by ceolter** [comment]
looks almost fine, but when i mentioned having it as an option, i meant as an option to the popup service. so it would be used always for the filters, but the option would be there not not have it on if the popup service was to be used someplace else in the future. if you can fix, that would be welcome, however i'm happy to fix it also. i think the gridOptions options is overkill, possibly confusing the gritOptions unnecessarily. my apologies if i confused things trying to explain the optional property.

**Comment by scotthovestadt** [comment]
@ceolter I've applied your feedback. Do you think it's OK to merge in now?

**Comment by ceolter** [comment]
cool. thanks.

**Pull request merged**
