### PR TITLE
Contribution & Browserify Refactor

### PR DESCRIPTION
**Pull request by tannerlinsley**

### CODE REVIEW

**Comment by tannerlinsley** [comment]
You'll see, there are a lot of big changes to the structure of the directory that conform to a more friendly open source pattern.  Directory names, package management, build process.

The website has been removed from the master build.  I suggest you create a separate fork called `gh-pages` for your website and online documentation.  Although you don't use github pages, this makes it obvious where the website is.

**Comment by tannerlinsley** [comment]
There is a very simple gulp build process that can easily be expanded upon for other stuff as well.

**Comment by derekperkins** [comment]
:+1:

**Comment by ceolter** [comment]
Had some conflicts with merge. Three files I edited in master were deleted in PR (although the changes I made were in the equivalent files in the PR so nothing was lost). I think the merge went fine otherwise.

**Pull request closed without merging**
