### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### ceolter/angular-grid now has a Chat Room on Gitter

@ceolter has just created a chat room. You can visit it here: [https://gitter.im/ceolter/angular-grid](https://gitter.im/ceolter/angular-grid?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/ceolter/angular-grid?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by thinkpadder1** [comment]
The gitter badge is missing now.

**Comment by ceolter** [comment]
i think i took it out, as i don't want to be involved in gitter!!! the amount of people answering questions was pretty much zero so it wasn't really a place for  me to go chat, it was more a distraction where my phone beeped every time someone had a question. i much prefer the forum or github, as it's non intrusive.

**Comment by thinkpadder1** [comment]
You can disable notifications. But, yea I understand. Thanks though! :)

**Comment by ceolter** [comment]
yes i could, but i don't want to get involved in chat rooms, i'm not making myself available for free support though chat rooms!

**Comment by thinkpadder1** [comment]
I don't see how it's different than your free forum... you could just create it and then not answer anything in them. Gitter is a lot easier to work with then registering for a forum and making a post.

**Pull request merged**
