### PR TITLE
Custom rowBuffer option, and scrolling optimizations

### PR DESCRIPTION
**Pull request by tannerlinsley**
- You can now define a custom rowBuffer in the gridOptions.
- Shaved off 3+ ms from rowRenderer by using native, non-function based
loops.

### CODE REVIEW

**Comment by ceolter** [comment]
hi Tanner

the for loop like this: (var i = -1; ++i < columns.length;)
goes against what's in the code elsewhere ie: (var i = 0; i<columns.length; i++)
second one i find more readable, easier to know what's going on (i prefer readable code over funky code). any reason to have it the way you have?

also, i'd rather (i!==0) over (!i) as the former is more readable (it reads as it means, whereas the !i depends on how javascript casts ints to booleans, hence doesn't read as well).

last question, using the transform instead of positioning, how much of a difference is this making for you performance wise? does it solve the problem completely, or just help a little?

and i lie, one more question!! i have been working on a branch, and have also done some refactoring in the scroll area. what is the process i should be following? if i merge my branch in first, do i then ask you to create a new pull request as the current one will have conflicts?

thanks :)

**Comment by tannerlinsley** [comment]
A for loop is performant over any callback style looper (which has to
execute a function for each loop, as opposed to just executing and
incrementing the index).  Legibility is negligible in my opinion here.
It's easy to see that it's a loop.  The only differences are the
optimizations in the parameters.  You can see the increment happens at the
condition stage, so you kill to birds with one stone.

(i== 0) == (!i). Of course, it's not an absolute comparison, but it i ===
undefined and not zero, you've got bigger problems here.

Transforming via '3dtranslate' layers the boxes in the DOM seperately, so
as to allow for faster redraws and relies on GPU acceleration when
possible.  It does smooth things up for me, but does not solve the problem
completely (see below).

The scrolling performance is not due to the number of scroll events that
build up.  It is simply the time of execution to update the dom
piggybacking on the table functions for updating rows and what not.  A
simply fix that I employed was to separate the vertical and horizontal
scroll events.  Vertical scrolling will need to update both the rows, and
pinned columns, but not the horizontal position of the header, which is the
only thing that happens on a horizontal scroll.  Once again, this improved
performance, but not enough to be exact.

The possible culprit of this problem could very well be the inertial
scrolling that happens on OSX, but I have yet to find out if that's true.

If you plan on merging my PR, do it before you do anything large.  It is
much more cumbersome for someone with an open PR to refactor and rebase
commits than it is for someone to submit a PR and handle any small
conflicts.

There are tons of ways to this, but personally like to handle merge
conflicts locally before they hit github, so this is what I would do:

- Merge my PR with master.
- Checkout and pull on master locally.
- Fork master to a new branch "A"
- Merge your custom branch into branch "A" (and handle the conflicts that
may arise)
- PR to github master with branch "A" (which shouldn't have any merge
conflicts at that point)
- After your PR gets merged into github master, checkout and pull on master
locally and you're all caught up.

I hope that makes sense.  I'm no expert, so if there is an easier way,
anyone else is more than welcome to chime in.

Also, I don't know what you use to resolve conflicts (or if you ever have
had to), but this sublime text plugin makes it dead simple:
https://packagecontrol.io/packages/Git%20Conflict%20Resolver

Just as "return often" applies to awesome code, my suggestion is
always: commit,
sync and release often.  It will keep merge hell from happening.

**Comment by ceolter** [comment]
"A for loop is performant over any callback style looper" - yes i know
that, my question was not asking why using a loop, my question was why
break from the standard "(init, check, increment)" layout of for loops. the
enhancement you put in by bunching the increment into the check is at best
negligible. a modern compiler should make this optimisation for you. hence
the way i would of done it (init, check, inc) makes more readable code.

re (i===0), again i think your missing my point here. the === implies type,
which makes the code more readable. probably not as big an issue as i is
defined near where the condition is, so you know it's type, however as a
rule of thumb, it makes code more difficult to read if you are depending on
implied types.

re merging - yes i agree - check in often to keep merging at a minimum.
however i was checking in often, but to my feature branch. i guess this is
a downfall of developing on feature branches and not against master.

i've just merged my feature branch into master. and as expected, you can
not non longer merge in your PR! the last time i fixed this by checking out
your PR, merging, then checking it back in, but i believe this changed the
history on who did the work, and you didn't get the credit for making the
change!

i have just merged my branch into master (all work done before you created
the PR - i didn't steal any ideas!!!)

i did already break out the updating of the scroll to horizontal and
vertical changes, but didn't notice any performance increase as a result.

can you please do the following:
- pull from master
- merge conflicts
- make following changes: a) use standard for-loop [init,check,inc] pattern
b) use (i===0)
- create new PR

thanks, :)

ps i do appreciate the work, using transform vs position looks interesting,
but i'm also trying to keep consistency in the style of coding.


On 26 April 2015 at 00:08, Tanner Linsley <notifications@github.com> wrote:

> A for loop is performant over any callback style looper (which has to
> execute a function for each loop, as opposed to just executing and
> incrementing the index). Legibility is negligible in my opinion here.
> It's easy to see that it's a loop. The only differences are the
> optimizations in the parameters. You can see the increment happens at the
> condition stage, so you kill to birds with one stone.
>
> (i== 0) == (!i). Of course, it's not an absolute comparison, but it i ===
> undefined and not zero, you've got bigger problems here.
>
> Transforming via '3dtranslate' layers the boxes in the DOM seperately, so
> as to allow for faster redraws and relies on GPU acceleration when
> possible. It does smooth things up for me, but does not solve the problem
> completely (see below).
>
> The scrolling performance is not due to the number of scroll events that
> build up. It is simply the time of execution to update the dom
> piggybacking on the table functions for updating rows and what not. A
> simply fix that I employed was to separate the vertical and horizontal
> scroll events. Vertical scrolling will need to update both the rows, and
> pinned columns, but not the horizontal position of the header, which is the
> only thing that happens on a horizontal scroll. Once again, this improved
> performance, but not enough to be exact.
>
> The possible culprit of this problem could very well be the inertial
> scrolling that happens on OSX, but I have yet to find out if that's true.
>
> If you plan on merging my PR, do it before you do anything large. It is
> much more cumbersome for someone with an open PR to refactor and rebase
> commits than it is for someone to submit a PR and handle any small
> conflicts.
>
> There are tons of ways to this, but personally like to handle merge
> conflicts locally before they hit github, so this is what I would do:
>
> - Merge my PR with master.
> - Checkout and pull on master locally.
> - Fork master to a new branch "A"
> - Merge your custom branch into branch "A" (and handle the conflicts that
> may arise)
> - PR to github master with branch "A" (which shouldn't have any merge
> conflicts at that point)
> - After your PR gets merged into github master, checkout and pull on master
> locally and you're all caught up.
>
> I hope that makes sense. I'm no expert, so if there is an easier way,
> anyone else is more than welcome to chime in.
>
> Also, I don't know what you use to resolve conflicts (or if you ever have
> had to), but this sublime text plugin makes it dead simple:
> https://packagecontrol.io/packages/Git%20Conflict%20Resolver
>
> Just as "return often" applies to awesome code, my suggestion is
> always: commit,
> sync and release often. It will keep merge hell from happening.
>
>
>
>
>
> On Sat, Apr 25, 2015 at 4:31 PM Niall Crosby <notifications@github.com>
> wrote:
>
> > hi Tanner
> >
> > the for loop like this: (var i = -1; ++i < columns.length;)
> > goes against what's in the code elsewhere ie: (var i = 0;
> > i<columns.length; i++)
> > second one i find more readable, easier to know what's going on (i prefer
> > readable code over funky code). any reason to have it the way you have?
> >
> > also, i'd rather (i!==0) over (!i) as the former is more readable (it
> > reads as it means, whereas the !i depends on how javascript casts ints to
> > booleans, hence doesn't read as well).
> >
> > last question, using the transform instead of positioning, how much of a
> > difference is this making for you performance wise? does it solve the
> > problem completely, or just help a little?
> >
> > and i lie, one more question!! i have been working on a branch, and have
> > also done some refactoring in the scroll area. what is the process i
> should
> > be following? if i merge my branch in first, do i then ask you to create
> a
> > new pull request as the current one will have conflicts?
> >
> > thanks :)
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ceolter/angular-grid/pull/94#issuecomment-96288794>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceolter/angular-grid/pull/94#issuecomment-96290178>.
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by ceolter** [comment]
I just applied the 'transform' trick locally, makes a huge difference for the header scrolling (i'd even say it fixes it on my android pad). However doesn't make any difference to the pinned column scrolling. So well done on the header bit! I didn't check it in though, I don't want to take credit for the work, I'll use the PR request your going to include with it!

**Comment by ceolter** [comment]
if you create something that requires the documents to be updated, can you
update the docs also please?

the item in the last PR was the new property, for setting the buffer size
in the virtual rows

thanks :)

On 26 April 2015 at 07:49, Niall Crosby <niall.crosby@gmail.com> wrote:

>
> "A for loop is performant over any callback style looper" - yes i know
> that, my question was not asking why using a loop, my question was why
> break from the standard "(init, check, increment)" layout of for loops. the
> enhancement you put in by bunching the increment into the check is at best
> negligible. a modern compiler should make this optimisation for you. hence
> the way i would of done it (init, check, inc) makes more readable code.
>
> re (i===0), again i think your missing my point here. the === implies
> type, which makes the code more readable. probably not as big an issue as i
> is defined near where the condition is, so you know it's type, however as a
> rule of thumb, it makes code more difficult to read if you are depending on
> implied types.
>
> re merging - yes i agree - check in often to keep merging at a minimum.
> however i was checking in often, but to my feature branch. i guess this is
> a downfall of developing on feature branches and not against master.
>
> i've just merged my feature branch into master. and as expected, you can
> not non longer merge in your PR! the last time i fixed this by checking out
> your PR, merging, then checking it back in, but i believe this changed the
> history on who did the work, and you didn't get the credit for making the
> change!
>
> i have just merged my branch into master (all work done before you created
> the PR - i didn't steal any ideas!!!)
>
> i did already break out the updating of the scroll to horizontal and
> vertical changes, but didn't notice any performance increase as a result.
>
> can you please do the following:
> - pull from master
> - merge conflicts
> - make following changes: a) use standard for-loop [init,check,inc]
> pattern b) use (i===0)
> - create new PR
>
> thanks, :)
>
> ps i do appreciate the work, using transform vs position looks
> interesting, but i'm also trying to keep consistency in the style of coding.
>
>
> On 26 April 2015 at 00:08, Tanner Linsley <notifications@github.com>
> wrote:
>
>> A for loop is performant over any callback style looper (which has to
>> execute a function for each loop, as opposed to just executing and
>> incrementing the index). Legibility is negligible in my opinion here.
>> It's easy to see that it's a loop. The only differences are the
>> optimizations in the parameters. You can see the increment happens at the
>> condition stage, so you kill to birds with one stone.
>>
>> (i== 0) == (!i). Of course, it's not an absolute comparison, but it i ===
>> undefined and not zero, you've got bigger problems here.
>>
>> Transforming via '3dtranslate' layers the boxes in the DOM seperately, so
>> as to allow for faster redraws and relies on GPU acceleration when
>> possible. It does smooth things up for me, but does not solve the problem
>> completely (see below).
>>
>> The scrolling performance is not due to the number of scroll events that
>> build up. It is simply the time of execution to update the dom
>> piggybacking on the table functions for updating rows and what not. A
>> simply fix that I employed was to separate the vertical and horizontal
>> scroll events. Vertical scrolling will need to update both the rows, and
>> pinned columns, but not the horizontal position of the header, which is
>> the
>> only thing that happens on a horizontal scroll. Once again, this improved
>> performance, but not enough to be exact.
>>
>> The possible culprit of this problem could very well be the inertial
>> scrolling that happens on OSX, but I have yet to find out if that's true.
>>
>> If you plan on merging my PR, do it before you do anything large. It is
>> much more cumbersome for someone with an open PR to refactor and rebase
>> commits than it is for someone to submit a PR and handle any small
>> conflicts.
>>
>> There are tons of ways to this, but personally like to handle merge
>> conflicts locally before they hit github, so this is what I would do:
>>
>> - Merge my PR with master.
>> - Checkout and pull on master locally.
>> - Fork master to a new branch "A"
>> - Merge your custom branch into branch "A" (and handle the conflicts that
>> may arise)
>> - PR to github master with branch "A" (which shouldn't have any merge
>> conflicts at that point)
>> - After your PR gets merged into github master, checkout and pull on
>> master
>> locally and you're all caught up.
>>
>> I hope that makes sense. I'm no expert, so if there is an easier way,
>> anyone else is more than welcome to chime in.
>>
>> Also, I don't know what you use to resolve conflicts (or if you ever have
>> had to), but this sublime text plugin makes it dead simple:
>> https://packagecontrol.io/packages/Git%20Conflict%20Resolver
>>
>> Just as "return often" applies to awesome code, my suggestion is
>> always: commit,
>> sync and release often. It will keep merge hell from happening.
>>
>>
>>
>>
>>
>> On Sat, Apr 25, 2015 at 4:31 PM Niall Crosby <notifications@github.com>
>> wrote:
>>
>> > hi Tanner
>> >
>> > the for loop like this: (var i = -1; ++i < columns.length;)
>> > goes against what's in the code elsewhere ie: (var i = 0;
>> > i<columns.length; i++)
>> > second one i find more readable, easier to know what's going on (i
>> prefer
>> > readable code over funky code). any reason to have it the way you have?
>> >
>> > also, i'd rather (i!==0) over (!i) as the former is more readable (it
>> > reads as it means, whereas the !i depends on how javascript casts ints
>> to
>> > booleans, hence doesn't read as well).
>> >
>> > last question, using the transform instead of positioning, how much of a
>> > difference is this making for you performance wise? does it solve the
>> > problem completely, or just help a little?
>> >
>> > and i lie, one more question!! i have been working on a branch, and have
>> > also done some refactoring in the scroll area. what is the process i
>> should
>> > be following? if i merge my branch in first, do i then ask you to
>> create a
>> > new pull request as the current one will have conflicts?
>> >
>> > thanks :)
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <https://github.com/ceolter/angular-grid/pull/94#issuecomment-96288794
>> >.
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ceolter/angular-grid/pull/94#issuecomment-96290178>.
>>
>
>
>
> --
> --
>
> The information transmitted is intended only for the person or entity to
> which it is addressed and may contain confidential and/or privileged
> material. Statements and opinions expressed in this e-mail may not
> represent those of the sender. Any review, retransmission, dissemination or
> other use of, or taking of any action in reliance upon, this information by
> persons or entities other than the intended recipient is prohibited. If you
> received this in error, please contact the sender immediately and delete
> the material from any computer.
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by tannerlinsley** [comment]
Don't merge yet.  Need to rebase.

**Pull request closed without merging**
