### PR TITLE
Adding the `suppressGroupRow` option

### PR DESCRIPTION
**Pull request by ocombe**
I also updated the docs accordingly.
I didn't include the docs/dist/angular-grid.js since you said that you will generate this yourself, but you'll need to generate it to test the example that I added into the documentation.

### CODE REVIEW

**Comment by ceolter** [comment]
PR accepted. I made some changes:

Changed docs a bit.

Changed suppressGroupRow to groupSuppressRow - to keep consistent with all the other group properties starting with 'group'.

The change is fine, and it works, however I think it doesn't properly demonstrate what this feature does. The example (appreciated btw) doesn't really get across what this feature is doing. To get it across, then would need to have the grid render somehow showing this.

One option would be to only populate the group cell for the first entry in the group. To do this, the node would need to have the 'child index'.

Another option would be to have a border at the bottom of each group?? (again, node would need a flat 'first in group' and / or 'last in group'.

Or could have a different background color for the group (would need node group index, then cell class could have odd / even colors for the group).

Anyway, I'm sure you have it implemented, exactly as you need it!!! So maybe this is for me to do :(

**Comment by ocombe** [comment]
ahah in fact I'll be implementing a different color for the group & a border around it, I didn't think that it was something that you might need and I was starting to make a complicated solution on my own.
I can make a new PR if you want ?
Do you have suggestions on how to do that ? By adding new parameters ? Or do you think that I can do this we what we have now ?

**Comment by ceolter** [comment]
ok i've just checked a headstart in.

now in the rowController, i tag each node with:
node.firstChild
node.lastChild
node.childIndex

because this is on the node, it is accessable to the callbacks that do the styling.

i updated your example, to highlight where the row is the first child.

i believe that's all that is needed FROM THE GRID. the rest of the work is up to the example to apply appropriate style based on what is presented here. do you want to work with that and improve the demo?

right, i've got to get to bed, nite.

**Comment by ocombe** [comment]
Sure I'll do that tomorrow, thanks ! :)

**Pull request merged**
